ID_TIPO_ALUNO_GRADUACAO = 1

ID_TIPO_LEITURA_LEITURA_DE_MATRICULA = 1
ID_TIPO_LEITURA_PAGAMENTO_TOTAL = 2
ID_TIPO_LEITURA_PAGAMENTO_SUBSIDIADO = 3

ID_TIPO_VINCULO_CATEGORIA_ALUNO_GRAD = 1
ID_TIPO_VINCULO_CATEGORIA_ALUNO_POS = 2