ID_TIPO_ALUNO_GRADUACAO = 1

ID_TIPO_LEITURA_LEITURA_DE_MATRICULA = 1
ID_TIPO_LEITURA_PAGAMENTO = 2

ID_TIPO_VINCULO_CATEGORIA_ALUNO_GRAD = 1
ID_TIPO_VINCULO_CATEGORIA_ALUNO_POS = 2

ID_TIPO_PRECO_TOTAL = 1
ID_TIPO_PRECO_DESCONTO = 2
